import type { FeatureId } from "../features/types.js";

/**
 * Result returned by the strategy evaluator.
 *
 * MATCH
 *   All required conditions for the strategy are satisfied.
 *
 * NO_MATCH
 *   Data is available, but the strategy conditions are not satisfied.
 *
 * NOT_READY
 *   Required feature data is warming up / missing / previous snapshot
 *   is unavailable for crossover calculations.
 */
export type StrategyEvaluationStatus = "MATCH" | "NO_MATCH" | "NOT_READY";

/**
 * Direction generated by the strategy.
 *
 * LONG  -> bullish setup
 * SHORT -> bearish setup
 */
export type StrategyDirection = "LONG" | "SHORT";

/**
 * Normal numeric comparison operators.
 */
export type ComparisonOperator = "GT" | "GTE" | "LT" | "LTE" | "EQ" | "NEQ";

/**
 * Operators that require the previous FeatureSnapshot.
 *
 * Example:
 *
 * previous:
 * EMA9 = 99
 * EMA21 = 100
 *
 * current:
 * EMA9 = 101
 * EMA21 = 100
 *
 * => CROSSES_ABOVE
 */
export type CrossOperator = "CROSSES_ABOVE" | "CROSSES_BELOW";

/**
 * Compare one feature against a fixed numeric value.
 *
 * Example:
 *
 * funding.rate < -0.0005
 */
export type FeatureValueCondition = {
  type: "FEATURE_VALUE";

  feature: FeatureId;

  operator: ComparisonOperator;

  value: number;
};

/**
 * Compare one feature against another feature.
 *
 * Example:
 *
 * EMA9 > EMA21
 */
export type FeatureFeatureCondition = {
  type: "FEATURE_FEATURE";

  left: FeatureId;

  operator: ComparisonOperator;

  right: FeatureId;
};

/**
 * Detect a real crossover between two features.
 *
 * IMPORTANT:
 * This requires both:
 *
 * previous FeatureSnapshot
 * current FeatureSnapshot
 *
 * so simply remaining above another EMA will NOT continuously
 * trigger CROSSES_ABOVE.
 */
export type CrossCondition = {
  type: "CROSS";

  left: FeatureId;

  operator: CrossOperator;

  right: FeatureId;
};

/**
 * ALL
 *
 * Every nested condition must match.
 *
 * Equivalent to logical AND.
 */
export type AllCondition = {
  type: "ALL";

  conditions: StrategyCondition[];
};

/**
 * ANY
 *
 * At least one nested condition must match.
 *
 * Equivalent to logical OR.
 */
export type AnyCondition = {
  type: "ANY";

  conditions: StrategyCondition[];
};

/**
 * NOT
 *
 * Inverts the result of the nested condition.
 */
export type NotCondition = {
  type: "NOT";

  condition: StrategyCondition;
};

/**
 * Recursive strategy condition tree.
 *
 * This allows strategies such as:
 *
 * ALL
 * ├── EMA9 > EMA21
 * ├── Funding < 0
 * └── ANY
 *     ├── OI Delta > 2%
 *     └── Volume Ratio > 1.5
 */
export type StrategyCondition =
  | FeatureValueCondition
  | FeatureFeatureCondition
  | CrossCondition
  | AllCondition
  | AnyCondition
  | NotCondition;

/**
 * Complete strategy definition.
 */
export type StrategyDefinition = {
  /**
   * Stable unique identifier.
   *
   * Example:
   * "mtf-ema-long"
   */
  id: string;

  /**
   * Human-readable strategy name.
   */
  name: string;

  /**
   * Optional explanation shown in UI later.
   */
  description?: string;

  /**
   * LONG or SHORT signal produced when the root condition matches.
   */
  direction: StrategyDirection;

  /**
   * Allows strategies to be disabled without deleting them.
   */
  enabled: boolean;

  /**
   * Root condition tree.
   */
  condition: StrategyCondition;

  /**
   * Optional metadata.
   *
   * Useful later for Strategy Builder UI,
   * categorisation and filtering.
   */
  tags?: string[];

  createdAt?: number;

  updatedAt?: number;
};

/**
 * Individual condition evaluation.
 *
 * Keeping a reason here is important because later the frontend
 * can explain WHY a strategy matched or failed.
 */
export type ConditionEvaluationResult = {
  status: StrategyEvaluationStatus;

  reason?: string;
};

/**
 * Final result for one strategy + one symbol.
 */
export type StrategyEvaluationResult = {
  strategyId: string;

  strategyName: string;

  symbol: string;

  direction: StrategyDirection;

  status: StrategyEvaluationStatus;

  evaluatedAt: number;

  /**
   * Human-readable explanation.
   *
   * Later this becomes:
   *
   * "EMA9 1H > EMA21 1H"
   * "Funding rate < -0.05%"
   * etc.
   */
  reason?: string;
};
